var st = require('st')
  , http = require('http')
  , path = require('path')
  , url = require('url')
  , os = require('os')
  , js = require('atomify-js')
  , css = require('atomify-css')
  , open = require('open')
  , through = require('through')
  , tinylr = require('tiny-lr-fork')
  , gaze = require('gaze')
  , colors = require('colors')
  , browserSync = require('browser-sync')
  , server
  , baseUrl
  , snippet

module.exports = function (args) {

  console.log('')

  var hostname = args.server.hostname || args.server.h ? os.hostname() + '.local' : 'localhost'
  args.server.url = args.server.url || 'http://' + hostname + ':1337/default'

  var mount = st(args.server.st || { path: process.cwd(), cache: false })
    , parsedUrl = url.parse(args.server.url)
    , port = args.server.port || parsedUrl.port
    , path = args.server.path || parsedUrl.path
    , lr = args.server.lr || args.server.l
    , launch = args.server.open || args.server.o

  if (args.server.sync || args.server.s) lr = {sync: true}

  baseUrl = parsedUrl.protocol + '//' + parsedUrl.hostname

  if (lr) {
    lr = typeof lr === 'boolean' ? {} : lr
    lr.patterns = lr.patterns || ['*.html', '*.js', '*.css']
    lr.port = lr.port || 3000
    lr.sync = parseSyncOptions(lr.sync || lr.s)
    startFileWatch(lr)
    console.log(('Live reload server listening on port ' + lr.port).grey)

    browserSync = browserSync.init(lr.patterns, {
      proxy: {
        host: parsedUrl.hostname,
        port: port
      }
      , ports: {
        min: lr.port,
        max: lr.port + 2
      }
      , injectChanges: false
      , ghostMode: lr.sync
      , debugInfo: Boolean(lr.verbose)
    }, function (err, config) {
      snippet = config.api.snippet;
    })
  }

  if (path.charAt(0) !== '/') path = '/' + path
  if (!args.js) args.js = {}
  if (!args.js.alias) args.js.alias = '/' + args.js.entry
  if (!args.css) args.css = {}
  if (!args.css.alias) args.css.alias = '/' + args.css.entry

  http.createServer(function (req, res) {

    switch (req.url.split('?')[0]) {
      case args.js.alias || args.js.entry:
        js(args.js, responder('javascript', res))
        break

      case args.css.alias || args.css.entry:
        css(args.css, responder('css', res))
        break

      case '/default':
        serveDefaultPage(res, args, lr)
        break

      default:
        if (lr && req.url.substr(-5) === '.html') res.filter = injectSnippet(lr)
        mount(req, res)
        break
    }

  }).listen(port)

  console.log(('Atomify server listening on port ' + port).grey)
  console.log('')

  if (launch) open(baseUrl + ':' + port + path)
}

function responder (type, res) {
  return function (err, src) {
    if (err) console.log(err);

    if (!res.headersSent) res.setHeader('Content-Type', 'text/' + type)
    res.end(src)
  }
}

function startFileWatch (lr) {
  gaze(lr.patterns, function () {
    this.on('changed', function (filepath) {
      if (!lr.quiet) console.log(path.relative(process.cwd(), filepath), 'changed'.grey);
      browserSync.events.emit('file:changed', {path: filepath});
    })
  })
}

function injectSnippet (lr) {
  var buffer = ''

  return through(function (chunk) {
    buffer += chunk.toString()
  }, function () {
    this.queue(buffer.replace('</body>', snippet + '</body>'))
    this.queue(null)
  })
}

function serveDefaultPage (res, args, lr) {
  var src = '<!doctype html><html><head>'
  src += '<meta charset="utf-8">'
  src += '<meta http-equiv="X-UA-Compatible" content="IE=edge">'
  src += '<meta name="viewport" content="initial-scale=1,width=device-width,user-scalable=0,minimal-ui">'
  src += '<title>generated by atomify</title>'
  if (args.css.entry) src += '<link rel="stylesheet" href="CSS">'
  src += '</head><body>'
  src += '<script src="JS"></script>'
  src += '</body></html>'

  src = src.replace('JS', args.js.alias)
  src = src.replace('CSS', args.css.alias)

  res.setHeader('Content-Type', 'text/html')

  var thru = lr ? injectSnippet(lr) : through()
  thru.pipe(res)
  thru.write(src)
  thru.end('\n')
}

function parseSyncOptions (opts) {
  if (!opts) return false
  if (typeof opts === 'object') return opts

  return {
    clicks: true
    , location: true
    , forms: true
    , scroll: true
  }
}
